  name: DemoNewCD
  on:
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Run a one-line script
          run: echo Running Build
    
    deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: daniel.dev.br
      needs: build
      steps:
        - name: Run a one-line script
          run: echo Deploy in DEV
    
    deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: hmg
        url: daniel.dev.br
      needs: deploy-dev
      steps:
        - name: Run a one-line script
          run:  echo Deploy in HMG
    
    deploy-prd:
      runs-on: ubuntu-latest
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      environment:
        name: prd
        url: daniel.dev.br
      needs: deploy-hmg
      steps:
        - name: Run a one-line script
          run: echo Deploy in PRD
#        - name: Run Snyk to check for vulnerabilities
#          uses: snyk/actions/maven@master
#          with:
#            command: code test
#        - name: Snyk Scan
#          uses: eeveebank/github-actions-snyk@1.0.6
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          with:
            command: monitor
