  name: DemoNewCD
  on:
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Run a one-line script
          run: echo Running Build
    
    deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: daniel.dev.br
      needs: build
      steps:
        - name: Run a one-line script
          run: echo Deploy in DEV
    
    deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: hmg
        url: daniel.dev.br
      needs: deploy-dev
      steps:
        - name: Run a one-line script
          run:  echo Deploy in HMG
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/maven@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         command: code test
    
    deploy-prd:
      runs-on: ubuntu-latest
      environment:
        name: prd
        url: daniel.dev.br
      needs: deploy-hmg
      steps:
        - name: Run a one-line script
          run: echo Deploy in PRD
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/maven@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         command: code test
    
    
